# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import graph_service_pb2 as graph__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGraphStats = channel.unary_unary(
                '/graphsched.GraphService/GetGraphStats',
                request_serializer=graph__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=graph__service__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.GetGraphEdges = channel.unary_unary(
                '/graphsched.GraphService/GetGraphEdges',
                request_serializer=graph__service__pb2.EdgesRequest.SerializeToString,
                response_deserializer=graph__service__pb2.EdgesResponse.FromString,
                _registered_method=True)


class GraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGraphStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGraphStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphStats,
                    request_deserializer=graph__service__pb2.StatsRequest.FromString,
                    response_serializer=graph__service__pb2.StatsResponse.SerializeToString,
            ),
            'GetGraphEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphEdges,
                    request_deserializer=graph__service__pb2.EdgesRequest.FromString,
                    response_serializer=graph__service__pb2.EdgesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graphsched.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('graphsched.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGraphStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graphsched.GraphService/GetGraphStats',
            graph__service__pb2.StatsRequest.SerializeToString,
            graph__service__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graphsched.GraphService/GetGraphEdges',
            graph__service__pb2.EdgesRequest.SerializeToString,
            graph__service__pb2.EdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
