# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'graph_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13graph_service.proto\x12\ngraphsched\"\x0e\n\x0cStatsRequest\";\n\rStatsResponse\x12\x10\n\x08num_pods\x18\x01 \x01(\x05\x12\x18\n\x10num_dependencies\x18\x02 \x01(\x05\"\x0e\n\x0c\x45\x64gesRequest\"U\n\tEdgeProto\x12\x12\n\nsource_uid\x18\x01 \x01(\t\x12\x12\n\ntarget_uid\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65p_type\x18\x03 \x01(\t\x12\x0e\n\x06weight\x18\x04 \x01(\x02\"5\n\rEdgesResponse\x12$\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x15.graphsched.EdgeProto2\x9a\x01\n\x0cGraphService\x12\x44\n\rGetGraphStats\x12\x18.graphsched.StatsRequest\x1a\x19.graphsched.StatsResponse\x12\x44\n\rGetGraphEdges\x12\x18.graphsched.EdgesRequest\x1a\x19.graphsched.EdgesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSREQUEST']._serialized_start=35
  _globals['_STATSREQUEST']._serialized_end=49
  _globals['_STATSRESPONSE']._serialized_start=51
  _globals['_STATSRESPONSE']._serialized_end=110
  _globals['_EDGESREQUEST']._serialized_start=112
  _globals['_EDGESREQUEST']._serialized_end=126
  _globals['_EDGEPROTO']._serialized_start=128
  _globals['_EDGEPROTO']._serialized_end=213
  _globals['_EDGESRESPONSE']._serialized_start=215
  _globals['_EDGESRESPONSE']._serialized_end=268
  _globals['_GRAPHSERVICE']._serialized_start=271
  _globals['_GRAPHSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
